config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: 'users/registrations' }
  root 'tasks#index'
  resources :tasks
  resources :projects
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/project.rb
class Project < ApplicationRecord
  has_many :tasks
  validates :name, :summary, :start_date, :end_date, presence: true
end

app/models/task.rb
class Task < ApplicationRecord
  belongs_to :project
  belongs_to :user
  validates :title, :description, :status, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  has_many :tasks
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :confirmable

  validates :first_name, :last_name, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  add_flash_types :success, :danger, :info, :warning
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]
  before_action :set_project, only: [ :show, :edit, :update, :destroy ]

  def index
    @projects = Project.all
  end

  def show
    @tasks = Task.where(project_id: [@project])
  end

  def new
    @project = Project.new
  end

  def create
    @project = Project.new(project_params)
    if @project.save
      redirect_to @project
    else
      flash.now[:danger] = 'Project not created'
      render :new
    end
  end

  def edit
  end

  def update
    if @project.update_attributes(project_params)
      redirect_to @project, success: 'Project successfully updated'
    else
      flash.now[:danger] = 'Project not updated'
      render :edit
    end
  end

  def destroy
    @project.destroy
    redirect_to projects_path, success: 'Project successfully deleted'
  end

  private

  def set_project
    @project = Project.find(params[:id])
  end

  def project_params
    params.require(:project).permit(:name, :summary, :start_date, :end_date)
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]
  before_action :set_task, only: [ :show, :edit, :update, :destroy ]

  def index
    @tasks = Task.all
  end

  def show
  end

  def new
    @task = Task.new
  end

  def create
    @task = Task.new(task_params)
    if @task.save
      redirect_to @task, success: 'Task successfully created'
    else
      flash.now[:danger] = 'Task not created'
      render :new
    end
  end

  def edit
  end

  def update
    if @task.update_attributes(task_params)
      redirect_to @task, success: 'Task successfully updated'
    else
      flash.now[:danger] = 'Task not updated'
      render :edit
    end
  end

  def destroy
    @task.destroy
    redirect_to tasks_path, success: 'Task successfully deleted'
  end

  private

  def set_task
    @task = Task.find(params[:id])
  end

  def task_params
    params.require(:task).permit(:title, :description, :status, :project_id, :user_id)
  end
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  before_action :configure_sign_up_params, only: [:create]
  before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

   protected

  # If you have extra params to permit, append them to the sanitizer.
  def configure_sign_up_params
   devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name])
   params.require(:user).permit(:first_name, :last_name, :email, :password, :password_confirmation)
  end

  # If you have extra params to permit, append them to the sanitizer.
  def configure_account_update_params
    devise_parameter_sanitizer.permit(:account_update, keys: [:first_name, :last_name])
  end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Projects list</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container">
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <a class="navbar-brand" href="#">Projects list</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item active">
            <a class="nav-link" href="<%= tasks_path %>">Tasks<span class="sr-only">(current)</span></a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="<%= projects_path %>">Projects</a>
          </li>
        </ul>
        <div class="nav-section pull-xs-right">
          <ul class="navbar-nav">
          <% if user_signed_in? %>
              <div class="buttons_panel">
                <%= link_to 'New task', new_task_path, class: 'btn btn-outline-primary pull-xs-right' %>
                <%= link_to 'New project', new_project_path, class: 'btn btn-outline-secondary pull-xs-right' %>
              </div>
            <li class="nav-item">
              <%= link_to "Sign out", destroy_user_session_path, method: :delete, class: "nav-link" %>
            </li>
          <% else %>
            <li class="nav-item">
              <%= link_to "Log in", new_user_session_path, class: "nav-link" %>
            </li>
            <li class="nav-item">
              <%= link_to "Sign up", new_user_registration_path, class: "nav-link" %>
            </li>
          <% end %>
          </ul>
        </div>
      </div>
    </nav>
  </div>
    <div class="container main">
      <div class="row">
        <div class="col-md-12">
          <% flash.each do |name, message| %>
            <div class="alert alert-<%= name %>">
              <button class="close" data-dismiss="alert">&times;</button>
              <%= message %>
            </div>
          <% end %>
        </div>
      </div>
      <%= yield %>
    </div>
  </body>
</html>

app/views/projects/_form.html.erb
<article class="form">
<% if @project.errors.any? %>
  <div class="alert alert-danger">
    <h5><%= t('common.errors') %></h5>
    <ul>
      <% @project.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>

<% end %>

<%= form_for @project do |f| %>
  <div class="form-group">
    <%= f.label :name %>
    <%= f.text_field :name, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.label :summary %>
    <%= f.text_area :summary, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.label :start_date %>
    <%= f.date_select :start_date, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.label :end_date %>
    <%= f.date_select :end_date, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.submit 'Save', class: 'btn btn-primary' %>
    <%= link_to 'Back', :back, class: 'btn btn-outline-secondary' %>
  </div>
<% end %>
</article>

app/views/projects/edit.html.erb
<h1>Edit project</h1>

<%= render 'form' %>

app/views/projects/index.html.erb
<h1>Projects</h1>

<section id="projects">
  <table class="table">
    <thead>
    <tr>
      <th>#</th>
      <th>Name</th>
      <th>Summary</th>
      <th>Start date</th>
      <th>End date</th>
      <th></th>
    </tr>
    </thead>
    <tbody>
    <% @projects.each_with_index do |project, index| %>
      <tr>
        <td><%= index + 1 %></td>
        <td><%=link_to project.name, project_path(project)  %></td>
        <td><%= project.summary %></td>
        <td><%= project.start_date.to_date.strftime("%d %B, %Y") %></td>
        <td><%= project.end_date.to_date.strftime("%d %B, %Y") %></td>
        <% if user_signed_in? %>
          <td>
            <%= link_to 'Edit', edit_project_path(project), class: 'btn btn-outline-primary btn-sm'  %>
            <%= link_to 'Delete', project_path(project), method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-outline-danger btn-sm'  %>
          </td>
        <% end %>
      </tr>
    <% end %>
    </tbody>
  </table>
</section>

app/views/projects/new.html.erb
<h1>New project</h1>

<%= render 'form' %>

app/views/projects/show.html.erb
<section class="project-head">
  <h1><%= @project.name %></h1>
  <small>
    <label>Start date </label>
    <time><%= @project.start_date.to_date.strftime("%d %B, %Y") %></time>
    |
    <label>End date </label>
    <time><%= @project.end_date.to_date.strftime("%d %B, %Y") %></time>
  </small>
</section>
<section class="project-summary">
  <%= @project.summary %>
</section>

<section id='tasks'>
  <table class="table">
    <thead>
    <tr>
      <th>#</th>
      <th>Title</th>
      <th>Description</th>
      <th>Status</th>
      <th>Responsible</th>
      <th>Date of create</th>
      <th></th>
    </tr>
    </thead>
    <tbody>
    <% @tasks.each_with_index do |task, index| %>
      <tr>
        <td><%= index + 1 %></td>
        <td><%=link_to task.title, task_path(task)  %></td>
        <td><%= task.description %></td>
        <td><%= task.status %></td>
        <td>
          <% if task.user.present? %>
            <%= task.user.first_name %>
            <%= task.user.last_name %>
          <% end %>
        </td>
        <td> <time><%= task.created_at.to_date.strftime("%d %B, %Y") %></time></td>
        <% if user_signed_in? %>
          <td>
            <%= link_to 'Edit', edit_task_path(task), class: 'btn btn-outline-primary btn-sm'  %>
            <%= link_to 'Delete', task_path(task), method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-outline-danger btn-sm'  %>
          </td>
        <% end %>
      </tr>
    <% end %>
    </tbody>
  </table>
</section>

app/views/tasks/_form.html.erb
<article class="form">
  <% if @task.errors.any? %>
    <div class="alert alert-danger">
      <h5><%= t('common.errors') %></h5>
      <ul>
        <% @task.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <%= form_for @task do |f| %>
    <div class="form-group">
      <div class="form-group">
        <%= f.label :project_id %>
        <%= f.collection_select :project_id, Project.order(:name), :id, :name, {include_blank: true}, class: 'form-control' %>
      </div>

      <%= f.label :title %>
      <%= f.text_field :title, class: 'form-control' %>
    </div>

    <div class="form-group">
      <%= f.label :description %>
      <%= f.text_area :description, class: 'form-control' %>
    </div>

    <div class="form-group">
      <%= f.label :status %>
      <%= f.select(:status, [['new'], ['in state'], ['done']])%>
    </div>

    <div class="form-group">
      <%= f.label :user_id %>
      <%= f.collection_select :user_id, User.order(:last_name), :id, :last_name, {include_blank: true}, class: 'form-control' %>
    </div>

    <div class="form-group">
      <%= f.submit 'Save', class: 'btn btn-primary' %>
      <%= link_to 'Back', :back, class: 'btn btn-outline-secondary' %>
    </div>
  <% end %>
</article>

app/views/tasks/edit.html.erb
<h1>Edit task</h1>

<%= render 'form' %>

app/views/tasks/index.html.erb
<h1>Tasks</h1>

<section id='tasks'>
  <table class="table">
    <thead>
    <tr>
      <th>#</th>
      <th>Project</th>
      <th>Title</th>
      <th>Description</th>
      <th>Status</th>
      <th>Responsible</th>
      <th>Date of create</th>
      <th></th>
    </tr>
    </thead>
    <tbody>
    <% @tasks.each_with_index do |task, index| %>
      <tr>
        <td><%= index + 1 %></td>
        <td>
          <% if task.project.present? %>
            <%= link_to task.project.name, task.project %>
          <% end %>
        </td>
        <td><%=link_to task.title, task_path(task)  %></td>
        <td><%= task.description %></td>
        <td><%= task.status %></td>
        <td>
          <% if task.user.present? %>
            <%= task.user.first_name %>
            <%= task.user.last_name %>
          <% end %>
        </td>
        <td> <time><%= task.created_at.to_date.strftime("%d %B, %Y") %></time></td>
        <% if user_signed_in? %>
          <td>
            <%= link_to 'Edit', edit_task_path(task), class: 'btn btn-outline-primary btn-sm'  %>
            <%= link_to 'Delete', task_path(task), method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-outline-danger btn-sm'  %>
          </td>
        <% end %>
      </tr>
    <% end %>
    </tbody>
  </table>
</section>

app/views/tasks/new.html.erb
<h1>New task</h1>

<%= render 'form' %>

app/views/tasks/show.html.erb
<article class="task">
  <section class="task-head">
    <h1><%= @task.title %></h1>
    <small>
      <time><%= @task.created_at.to_date.strftime("%d %B, %Y") %></time>
      <% if @task.project.present? %>
        |
        <%= link_to @task.project.name, @task.project %>
      <% end %>
      <% if user_signed_in? %>
      |
      <%= link_to 'Edit', edit_task_path(@task) %>
      |
      <%= link_to 'Delete', task_path(@task), method: :delete, data: { confirm: 'Вы уверены?' } %>
      <% end %>
    </small>
  </section>

  <section class="task-responsible">
    <label>Responsible:</label>
    <%= @task.user.first_name %>
    <%= @task.user.last_name %>
  </section>

  <section class="task-status">
    <label>Status:</label>
    <%= @task.status %>
  </section>

  <section class="task-description">
    <%= @task.description %>
  </section>
</article>